services:
  server:
    image: paulgoio/searxng:production
    container_name: searxng
    environment:
      #- SEARXNG_BASE_URL=http://localhost:8080
      - INSTANCE_NAME=searxng
    restart: always
    volumes:
      - ./searx/settings.yml:/usr/local/searxng/searx/settings.yml
    ports:
      - 8090:8080
