name: Docker test

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - /home/runner:/home/runner 
      options: --cpus 1

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Create Custom User With secrets    
        shell: bash
        run: |
          apt-get update
          apt-get install -y openssh-server tmux zsh sudo
    
          adduser --disabled-password --gecos "" "$MY_SSH_USER"
          usermod -a -G sudo "$MY_SSH_USER"
          echo $MY_SSH_USER:$MY_SSH_PSW |   chpasswd

          # tmux new-session -s mySession -d
          # tmux new -d -s mySession
          # tmux new-session -s mySession -d 
          
          # tmux send-keys -t mySession.0 "ssh -o StrictHostKeyChecking=no $MY_SSHJ_NS@ssh-j.com -N -R $MY_SSHJ_HOST:22:localhost:22" ENTER
          # tmux a -t mySession


          # run sshd 
          mkdir  /var/run/sshd
          /usr/sbin/sshd -D
          ssh -o "StrictHostKeyChecking no" $MY_SSHJ_NS@ssh-j.com -N -R $MY_SSHJ_HOST:22:localhost:22
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}      
          MY_SSH_USER: ${{secrets.MY_SSH_USER}}
          MY_SSH_PSW: ${{secrets.MY_SSH_PSW}}
          MY_SSHJ_NS: ${{secrets.MY_SSHJ_NS}}
          MY_SSHJ_HOST: ${{secrets.MY_SSHJ_HOST}}


          


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo github.workspace : ${{ github.workspace }} 
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
      
      - name: Make a file with a lot of repeated text
        run: |
          mkdir  ${{ steps.strings.outputs.build-output-dir }}
          for i in {1..1000}; do echo -n 'foobar' >> ${{ steps.strings.outputs.build-output-dir }}/foobar.txt; done
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ steps.strings.outputs.build-output-dir }}/*
          compression-level: 9 # maximum compression
