# This is a basic workflow to help you get started with Actions

name: start_dev

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    #schedule:
    # https://github.com/orgs/community/discussions/13454#discussioncomment-11159669
    #- cron: '47 */1 * * *'

jobs:
  start_dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /tmp
    steps:
      - name: Set current date as env variable
        run: |
          echo "START_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          echo "STAMP=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
  
          start_time=$(date +%s)
          end_time=$((start_time+6*3600-1000))
  
          echo "RUNNER_START_STAMP=$start_time" >> $GITHUB_ENV
          echo "RUNNER_END_STAMP=$end_time" >> $GITHUB_ENV